# ============================================================
# Mosquitto MQTT Broker Configuration
# Smart City IoT — Nocturnal Poison Platform
# Port: 1883 (MQTT) | 9001 (WebSocket untuk Node-RED UI)
# ============================================================

# Listener 
listener 1883
protocol mqtt

# WebSocket listener (untuk debug via browser)
listener 9001
protocol websockets

# Autentikasi 
allow_anonymous true



# Persistence
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S

# Connection Settings
max_connections 100
max_keepalive 60

