apiVersion: v1
kind: ConfigMap
metadata:
  name: smartcity-config
  namespace: smartcity
data:
  # Service URLs 
  CITIZEN_SERVICE_URL: "http://php-citizen-service:8000"
  TRAFFIC_SERVICE_URL: "http://php-traffic-service:8001"
  ENV_SERVICE_URL: "http://php-environment-service:8002"
  PYTHON_ML_URL: "http://python-ml-service:5000"
  OAUTH_SERVER_URL: "http://oauth-server-service:3002"

  # MySQL
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "smartcity"
  DB_USER: "root"

  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"

  # ML
  MODEL_PATH: "models/"

  # JWT
  JWT_EXPIRES_IN: "3600"

  # App
  APP_ENV: "production"