apiVersion: v1
kind: Service
metadata:
  name: php-citizen-service
  namespace: smartcity
spec:
  selector:
    app: php-citizen
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-citizen
  namespace: smartcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-citizen
  template:
    metadata:
      labels:
        app: php-citizen
    spec:
      containers:
        - name: php-citizen
          image: smartcity/php-citizen:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: smartcity-config
                  key: APP_ENV
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: smartcity-secrets
                  key: app-key
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: smartcity-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: smartcity-config
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: smartcity-config
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: smartcity-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartcity-secrets
                  key: mysql-root-password
            # untuk processLungDegradation
            - name: ENV_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: smartcity-config
                  key: ENV_SERVICE_URL
            - name: PYTHON_ML_URL
              valueFrom:
                configMapKeyRef:
                  name: smartcity-config
                  key: PYTHON_ML_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10