apiVersion: v1
kind: Secret
metadata:
  name: smartcity-secrets
  namespace: smartcity
type: Opaque
stringData:
  mysql-root-password: "REPLACE_ME"
  mysql-database: "smartcity"
  jwt-secret: "REPLACE_ME"
  rabbitmq-user: "REPLACE_ME"
  rabbitmq-pass: "REPLACE_ME"
  app-key: "REPLACE_ME"