apiVersion: v1
kind: Secret
metadata:
  name: smartcity-secrets
  namespace: smartcity
type: Opaque
stringData:
  mysql-root-password: "rootpass"
  mysql-database: "smartcity"
  jwt-secret: "your_jwt_secret_here"
  rabbitmq-user: "guest"
  rabbitmq-pass: "guest"
  app-key: "base64:IdvzeDrlaaY5FqxUDxwPo2iabDjBa0UK/RSul9mcnHk="